# -*- coding: utf-8 -*-
"""Grading program

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sp-klhzbBgP7PJ-1GWP-j5lBTcx_kiW3
"""

def score(percentage):
  if percentage>=90:
    return "A"
  elif percentage>=80:
    return "B"
  elif percentage>=70:
    return "C"
  elif percentage>=60:
    return "D"
  else:
    return "F"
def calculate_avg(students):
  total = 0
  for student_data in students:
    total += student_data["percentage"]
  return total/len(students)
def highest_scorer(students):
  if not students:
    return None # Handle empty list case
  top = students[0]
  for student_data in students:
    if student_data["percentage"] > top["percentage"]:
      top = student_data
  return top # Return outside the loop
def lowest_scorer(students):
  if not students:
    return None # Handle empty list case
  low = students[0]
  for student_data in students:
    if student_data["percentage"] < low["percentage"]:
      low = student_data
  return low # Return outside the loop

all_students = [] # Renamed the list variable to avoid shadowing
num_student = int(input("Enter number of students taking part in the test"))
for i in range(num_student):
  print(f"\nStudents{i+1}")
  name = input("Enter student's name")
  percentage = int(input("Percentage scored"))
  all_students.append({
      "name" : name,
      "percentage" : percentage
  })

print("\n student report\n")
for student_data in all_students: # Iterate using a different variable name
  grade = score(student_data["percentage"])
  print(
      f"Name:{student_data['name']}|"
      f"Percentage:{student_data['percentage']}|"
      f"Grade:{grade}"
  )

print("\nSummary")
avg = calculate_avg(all_students) # Pass the correct list variable
top = highest_scorer(all_students)
low = lowest_scorer(all_students)

print(f"Average Percentage: {avg}")
if top:
  print(f"Highest Scorer: {top['name']} with {top['percentage']}%")
if low:
  print(f"Lowest Scorer: {low['name']} with {low['percentage']}%")